2020/10/29 21:50:31 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2020/10/29 21:50:31 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2020/10/30 12:59:01 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2020/10/30 12:59:03 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2020/10/30 12:59:04 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2020/10/30 12:59:16 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2020/10/30 12:59:17 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "localhost"
2020/11/02 13:21:10 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost"
2020/11/02 13:21:10 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost", referrer: "http://localhost/"
2020/11/02 13:21:11 [error] 28#28: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost"
2020/11/03 13:58:35 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /nysa HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost", referrer: "http://localhost/"
2020/11/03 13:59:10 [error] 28#28: *4 FastCGI sent in stderr: "PHP message: 2020-11-03T13:59:10+00:00 [critical] Uncaught Exception: Unrecognized option "_errors" under "framework". Available options are "annotations", "assets", "cache", "csrf_protection", "default_locale", "disallow_search_engine_index", "error_controller", "esi", "form", "fragments", "http_client", "http_method_override", "ide", "lock", "mailer", "messenger", "notifier", "php_errors", "profiler", "property_access", "property_info", "request", "router", "secret", "secrets", "serializer", "session", "ssi", "test", "translator", "trusted_hosts", "validation", "web_link", "workflows"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /nysa HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost", referrer: "http://localhost/"
2020/11/03 22:01:20 [error] 28#28: *187 FastCGI sent in stderr: "PHP message: 2020-11-03T22:01:20+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Controller\DefaultController": argument "$reportService" of method "__construct()" references interface "App\Services\ReportServiceInterface" but no such service exists. Did you create a class that implements this interface?" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /moskwa HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost"
2020/11/09 10:58:20 [error] 29#29: *53 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost"
2020/11/09 10:58:29 [error] 29#29: *53 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost"
2020/11/09 10:58:43 [error] 29#29: *53 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost"
